<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>

    <xacro:property name="chassis_length" value="0.49"/>
    <xacro:property name="chassis_width" value="0.49"/>
    <xacro:property name="chassis_height" value="0.15"/>
    <xacro:property name="chassis_mass" value="5.0"/>
    <xacro:property name="wheel_radius" value="0.06"/>
    <xacro:property name="wheel_thickness" value="0.06"/>
    <xacro:property name="wheel_mass" value="0.2"/>
    <xacro:property name="wheel_offset_x" value="0.226"/>
    <xacro:property name="wheel_offset_y" value="0.1485"/>
    <xacro:property name="wheel_offset_z" value="0.01"/>
    <xacro:property name="caster_wheel_radius" value="0.01"/>
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <material name="blue">
      <color rgba="0 0 0.8 1"/>
    </material>
    <material name="white">
      <color rgba="1 1 1 1"/>
    </material>
    <material name="black">
      <color rgba="0 0 0 1"/>
    </material>
    <material name="green">
        <color rgba="0.0 0.8 0.0 1.0"/>
    </material>

    <!-- BASE LINK -->
    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>

    <!--CHASSIS OF THE ROBOT-->
    <link name="chassis_link">
        <visual>
            <geometry>
                <box size="0.49 0.49 0.15"/>
            </geometry>
            <material name="white"/>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </visual>
        <collision>
            <geometry>
                <box size="0.49 0.49 0.15"/>
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
        </collision>
        <xacro:inertial_box mass="5" x="0.49" y="0.49" z="0.15">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="chassis_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="chassis_link" />
        <axis xyz="0 0 0" />
    </joint>

    <gazebo reference="chassis_link">
      <material>Gazebo/Orange</material>
    </gazebo>

    <!--RIGHT WHEEL-->
    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.06" length="0.06"/>
            </geometry>
            <material name="black"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="0.06"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="0.06" radius="0.06">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
      
    <joint name="right_wheel_joint" type="continuous">
        <origin xyz="0 -0.29 -0.09" rpy="-1.5708 0 0" />
        <parent link="base_link" />
        <child link="right_wheel" />
        <axis xyz="0 0 1" />
    </joint>

    <gazebo reference="right_wheel">
      <material>Gazebo/Black</material>
    </gazebo>

    <!--LEFHT WHEEL-->
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="0.06" length="0.06"/>
            </geometry>
            <material name="black"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="0.06"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.2" length="0.06" radius="0.06">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
      
    <joint name="left_wheel_joint" type="continuous">
        <origin xyz="0 0.29 -0.09" rpy="-1.5708 0 0" />
        <parent link="base_link" />
        <child link="left_wheel" />
        <axis xyz="0 0 1" />
    </joint>

    <gazebo reference="left_wheel">
      <material>Gazebo/Black</material>
    </gazebo>
    
    <!--CASTER_WHEEL-->
    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="0.035"/>
            </geometry>
            <material name="green"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="0.035"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="0.035">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
      
    <joint name="caster_wheel_joint" type="fixed">
        <origin xyz="-0.24 0 -0.110" rpy="0 0 0" />
        <parent link="chassis_link" />
        <child link="caster_wheel" />
        <axis xyz="0 0 0" />
    </joint>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Green</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <!--CASTER_WHEEL2-->
    <link name="caster_wheel2">
        <visual>
            <geometry>
                <sphere radius="0.035"/>
            </geometry>
            <material name="green"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <sphere radius="0.035"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="0.035">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>
      
    <joint name="caster_wheel_joint2" type="fixed">
        <origin xyz="0.24 0 -0.110" rpy="0 0 0" />
        <parent link="chassis_link" />
        <child link="caster_wheel2" />
        <axis xyz="0 0 0" />
    </joint>

    <gazebo reference="caster_wheel2">
        <material>Gazebo/Green</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
    
    <!--LIGHT TUBE-->
    <link name="light_tube">
        <visual>
            <geometry>
                <box size="0.1 0.1 1.0"/>
            </geometry>
            <material name="blue"/>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </visual>
        <collision>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <geometry>
                <box size="0.1 0.1 1.0"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="3" x="0.1" y="0.1" z="1.0">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
      
    <joint name="light_tube_joint" type="fixed">
        <origin xyz="0.0 0.0 0.575" rpy="0 0 0" />
        <parent link="chassis_link" />
        <child link="light_tube" />
        <axis xyz="0 0 0" />
    </joint>
    
    <gazebo reference="light_tube">
      <material>Gazebo/Blue</material>
    </gazebo>

</robot>